{"uuid": "b8741937-76c7-4e80-baad-931935623a86", "children": ["6d67281a-1608-4d74-9a78-74f32c307725"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=124.0.6367.93)\nStacktrace:\n0   chromedriver                        0x000000010a489a18 chromedriver + 5216792\n1   chromedriver                        0x000000010a481653 chromedriver + 5183059\n2   chromedriver                        0x0000000109ff3527 chromedriver + 406823\n3   chromedriver                        0x0000000109fc956e chromedriver + 234862\n4   chromedriver                        0x000000010a06a02d chromedriver + 892973\n5   chromedriver                        0x000000010a080038 chromedriver + 983096\n6   chromedriver                        0x000000010a0614a3 chromedriver + 857251\n7   chromedriver                        0x000000010a031fe3 chromedriver + 663523\n8   chromedriver                        0x000000010a03292e chromedriver + 665902\n9   chromedriver                        0x000000010a447930 chromedriver + 4946224\n10  chromedriver                        0x000000010a44d9e4 chromedriver + 4970980\n11  chromedriver                        0x000000010a42842e chromedriver + 4817966\n12  chromedriver                        0x000000010a44e4f9 chromedriver + 4973817\n13  chromedriver                        0x000000010a4186b4 chromedriver + 4753076\n14  chromedriver                        0x000000010a470ba8 chromedriver + 5114792\n15  chromedriver                        0x000000010a470d67 chromedriver + 5115239\n16  chromedriver                        0x000000010a481273 chromedriver + 5182067\n17  libsystem_pthread.dylib             0x00007ff81b5e5202 _pthread_start + 99\n18  libsystem_pthread.dylib             0x00007ff81b5e0bab thread_start + 15\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/standard/Desktop/Tobeto-Test-Team-Project/tests/conftest.py\", line 49, in setup\n    driver.maximize_window()\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 499, in maximize_window\n    self.execute(command, None)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1714735891010, "stop": 1714735896136}], "start": 1714735891010, "stop": 1714735896196}