{"uuid": "33fd11f4-48b7-49ce-b079-a3d2bfdb9959", "children": ["0c8651b8-69c1-4378-bfb2-8a3bdebe87be"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=124.0.6367.93)\nStacktrace:\n0   chromedriver                        0x000000010b273a18 chromedriver + 5216792\n1   chromedriver                        0x000000010b26b653 chromedriver + 5183059\n2   chromedriver                        0x000000010addd527 chromedriver + 406823\n3   chromedriver                        0x000000010adb356e chromedriver + 234862\n4   chromedriver                        0x000000010ae5402d chromedriver + 892973\n5   chromedriver                        0x000000010ae6a038 chromedriver + 983096\n6   chromedriver                        0x000000010ae4b4a3 chromedriver + 857251\n7   chromedriver                        0x000000010ae1bfe3 chromedriver + 663523\n8   chromedriver                        0x000000010ae1c92e chromedriver + 665902\n9   chromedriver                        0x000000010b231930 chromedriver + 4946224\n10  chromedriver                        0x000000010b2379e4 chromedriver + 4970980\n11  chromedriver                        0x000000010b21242e chromedriver + 4817966\n12  chromedriver                        0x000000010b2384f9 chromedriver + 4973817\n13  chromedriver                        0x000000010b2026b4 chromedriver + 4753076\n14  chromedriver                        0x000000010b25aba8 chromedriver + 5114792\n15  chromedriver                        0x000000010b25ad67 chromedriver + 5115239\n16  chromedriver                        0x000000010b26b273 chromedriver + 5182067\n17  libsystem_pthread.dylib             0x00007ff81b5e5202 _pthread_start + 99\n18  libsystem_pthread.dylib             0x00007ff81b5e0bab thread_start + 15\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/standard/Desktop/Tobeto-Test-Team-Project/tests/conftest.py\", line 49, in setup\n    driver.maximize_window()\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 499, in maximize_window\n    self.execute(command, None)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1714735896277, "stop": 1714735901807}], "start": 1714735896277, "stop": 1714735901870}